# $Id$
#
# Copyright (C) 1999-2003 Jens Thoms Toerring
#
# Template file for Makefiles to create the modules that need to be made
# from more than one source file plus a header file. The '##'s get
# replaced by the module name when the real Makefile is created from
# this template file.
#
# This file is part of fsc2.
#
# Fsc2 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# Fsc2 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with fsc2; see the file COPYING.  If not, write to
# the Free Software Foundation, 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.


# See the comments for the correspondig rules for simple modules
# on why these rules have this rather complicated form.

##.so: $(##:.c=.o)
	if [ -z "$($(patsubst %.so,%_libs,$@))" ]; then              \
		$(CC) $(LFLAGS) $^ -o $@;                                \
		chmod 644 $@;                                            \
	else                                                         \
		for l in "$($(patsubst %.so,%_libs,$@))"; do             \
			if [ "$(notdir $$l)" == "$$l" ]; then                \
				l=$${l%.so};                                     \
				libs="$$libs -l$${l#lib}";                       \
			else                                                 \
				libs="$$libs $$l";                               \
			fi;                                                  \
		done;                                                    \
		$(CC) $$libs -shared -o $@.lib_test 2>/dev/null;         \
		if [ -e $@.lib_test ]; then                              \
			$(RM) $(RMFLAGS) $@.lib_test;                        \
			$(CC) $(LFLAGS) $^ $$libs -o $@;                     \
			chmod 644 $@;                                        \
		fi;                                                      \
	fi

$(##:.c=.o): %.o: %.c ##.h $(cdir)/##.conf $(src_headers)
	incl="$(foreach i,$(##_incl),-I$(i))";                       \
	$(CC) $(CFLAGS) -c $(LFLAGS) $< -o $@

# The replacement of 'ECHO' by 'FLEX_ECHO' in the files created by flex is
# done because 'ECHO' (that is #defined in these files) is already defined
# in termios.h. The second replacement is for avoiding compiler warnings
# about unitialized variables in these files.

%_lexer.c: %_lexer.l $(src_header)
	$(FLEX) $(FLEXFLAGS)$(patsubst %lexer.l,%,$<) -o$@ $<
	sed -e 's/\bECHO\b/FLEX_ECHO/g' $@ > $@.x
	sed -e 's/register char \*yy_cp, \*yy_bp;/\
			register char \*yy_cp = NULL, \*yy_bp = NULL;/' $@.x > $@
	-$(RM) $(RMFLAGS) $@.x
