#!/usr/bin/perl
# -*- cperl -*-
#
# Copyright (C) 1999-2011 Jens Thoms Toerring
#
# This file is part of fsc2.
#
# Fsc2 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.
#
# Fsc2 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


use strict;
use warnings;
use Tk;
use Tk::Balloon;
use POSIX;

my @version = split /\./, $Tk::VERSION;
die "Installed Perl-Tk version is $Tk::VERSION but Tk800.022 is required.\n"
    if $version[ 0 ] + 0.001 * $version[ 1 ] < 800.022;


my $ER032M_MIN_FIELD             = -50.0;
my $ER032M_MAX_FIELD             = 23000.0;
my $ER032M_MAX_SWEEP_WIDTH       = 16000.0;
my $ER032M_MIN_FIELD_STEP        = 1e-3;


my $field              = 3350;
my $tc                 = "Don't set";
my $sens1              = "Don't set";
my $old_sens1          = $sens1;
my $sens2              = "E+3";
my $old_sens2          = $sens2;
my $phase;
my $mod_freq           = "Don't set";
my $mod_amp            = "";
my $sec_freq           = "";
my $how                = 'Start experiment';


my %fp = ( '-side' => 'top',
           '-fill' => 'x',
           '-padx' => '2m',
           '-pady' => '2m' );

my %wp = ( '-side' => 'left',
           '-fill' => 'x',
           '-padx' => '3m',
           '-expand' => 1 );

# Get defaults

&get_defs;

# Create all the graphic stuff

my $mw = MainWindow->new( );
$mw->title( "cw_epr" );
my $balloon = $mw->Balloon( );


my $f1 = $mw->Frame( );
my $f1_l1 = $f1->Label( '-text'           => 'Field:',
                        '-width'          => '20',
                        '-anchor'         => 'w' );
my $f1_v = $f1->Entry( '-textvariable'    => \$field,
                       '-width'           => '8',
                       '-validate'        => 'key',
                       '-validatecommand' => \&is_numeric,
                       '-relief'          => 'sunken' );
$balloon->attach( $f1_v, '-balloonmsg'    =>
                         "Enter the field (in Gauss)" );
my $f1_l2 = $f1->Label( '-text'           => 'G',
                        '-width'          => 1 );

$f1->pack( %fp );
$f1_l1->pack( %wp );
$f1_v->pack( %wp );
$f1_l2->pack( %wp );


my $f10 = $mw->Frame( );
my $f10_l = $f10->Label( '-text'          => 'Amplification:',
                         '-width'         => '20',
                         '-anchor'       => 'w' );
my $f10_m1 = $f10->Optionmenu( '-options'  =>
                               [ ( "Don't set", '1.0', '1.25', '1.5', '2.0',
                                   '2.5', '3.0', '4.0', '5.0', '6.0',
                                   '8.0' ) ],
                               '-width'    => 7,
                               '-textvariable' => \$sens1,
                               '-command' => \&sens_check );
$balloon->attach( $f10_m1, '-balloonmsg' =>
                  "Select the lock-in amplifiers amplification factor" );
my $f10_m2 = $f10->Optionmenu( '-options'  =>
                               [ ( 'E+1', 'E+2', 'E+3', 'E+4', 'E+5', 'E+6',
                                   'E+7' ) ],
                               '-width'    => 3,
                               '-textvariable' => \$sens2,
                               '-command' => \&sens_check );
$balloon->attach( $f10_m2, '-balloonmsg' =>
                  "Select the lock-in amplifiers amplification factor" );

$f10->pack( %fp );
$f10_l->pack( %wp );
$f10_m1->pack( %wp );
$f10_m2->pack( %wp );


my $f9 = $mw->Frame( );
my $f9_l = $f9->Label( '-text'          => 'Time constant (tc):',
                       '-width'         => '20',
                       '-anchor'        => 'w' );
my $f9_m = $f9->Optionmenu( '-options'  =>
                            [ ( "Don't set", '2.5 ms', '5 ms', '10 ms',
                                '20 ms', '40 ms', '80 ms', '160 ms', '320 ms',
                                '640 ms', '1.25 s', '2.5 s', '5 s' ) ],
                            '-width'    => 9,
                            '-textvariable' => \$tc );
$balloon->attach( $f9_m, '-balloonmsg' =>
                         "Select the lock-in amplifiers time constant" );
$f9->pack( %fp );
$f9_l->pack( %wp );
$f9_m->pack( %wp );


my $f4 = $mw->Frame( );
my $f4_l1 = $f4->Label( '-text'           => 'Phase:',
                        '-width'          => '20',
                        '-anchor'         => 'w' );
my $f4_v = $f4->Entry( '-textvariable'    => \$phase,
                       '-width'           => '8',
                       '-validate'        => 'key',
                       '-validatecommand' => sub { $_[ 0 ] =~ /^[+-]?\d*$/ },
                       '-relief'          => 'sunken' );
my $f4_l2 = $f4->Label( '-text'           => ' ',
                        '-width'          => 1 );
$balloon->attach( $f4_v, '-balloonmsg'    =>
                  "Set the lock-in amplifiers phase"  );
$f4->pack( %fp );
$f4_l1->pack( %wp );
$f4_v->pack( %wp );
$f4_l2->pack( %wp );

my $f5 = $mw->Frame( );
my $f5_l = $f5->Label( '-text'          => 'Modulation frequency:',
                       '-width'         => '20',
                       '-anchor'        => 'w' );
my $f5_m = $f5->Optionmenu( '-options'  =>
                            [ ( "Don't set", '100 kHz', '50 kHz', '25 kHz',
                                '12.5 kHz', '6.25 kHz', '3.125 kHz',
							    '1.5625 kHz' )],
                            '-width'    => 9,
                            '-textvariable' => \$mod_freq );
$balloon->attach( $f5_m, '-balloonmsg' =>
                         "Select the lock-in modulation frequency" );
$f5->pack( %fp );
$f5_l->pack( %wp );
$f5_m->pack( %wp );

my $f8 = $mw->Frame( );
my $f8_l1 = $f8->Label( '-text'           => 'Modulation amplitude:',
                        '-width'          => '20',
                        '-anchor'         => 'w' );
my $f8_v = $f8->Entry( '-textvariable'    => \$mod_amp,
                       '-width'           => '8',
                       '-validate'        => 'key',
                       '-validatecommand' => \&is_numeric,
                       '-relief'          => 'sunken' );
my $f8_l2 = $f8->Label( '-text'           => 'G',
                        '-width'          => 1 );
$balloon->attach( $f8_v, '-balloonmsg'    =>
                  "Set the lock-in amplifiers modulation amplitude\n" );
$f8->pack( %fp );
$f8_l1->pack( %wp );
$f8_v->pack( %wp );
$f8_l2->pack( %wp );


my $f12 = $mw->Frame( );
my $f12_l1 = $f12->Label( '-text'           => 'Chopper sector freq.:',
						  '-width'          => '20',
						  '-anchor'         => 'w' );
my $f12_v = $f12->Entry( '-textvariable'    => \$sec_freq,
						 '-width'           => '8',
						 '-validate'        => 'key',
						 '-validatecommand' => \&is_numeric,
						 '-relief'          => 'sunken' );
my $f12_l2 = $f12->Label( '-text'           => 'Hz',
						  '-width'          => 1 );
$balloon->attach( $f12_v, '-balloonmsg'    =>
                  "Set the chopper's sector rotation frequency\n" );
$f12->pack( %fp );
$f12_l1->pack( %wp );
$f12_v->pack( %wp );
$f12_l2->pack( %wp );


$mw->Optionmenu( '-options' => [ ( 'Start experiment', 'Test program',
                                   'Load into fsc2' ) ],
                 '-textvariable' => \$how,
               )->pack( '-padx' => '3m',
                        '-pady' => '3m' );

my $f11 = $mw->Frame( );
my $f11_a = $mw->Button( '-text' => 'Apply',
                         '-command' => \&write_out );
my $f11_q = $mw->Button( '-text' => 'Quit',
                         '-command' => sub { &store_defs; $mw->destroy } );
$f11->pack( '-side' => 'top',
            '-fill' => 'x',
            '-padx' => '4m' );
$f11_a->pack( %wp, '-padx' => '5m', '-pady' => '3m' );
$f11_q->pack( %wp, '-padx' => '5m', '-pady' => '3m' );

MainLoop;


#############################################

sub get_defs {

    my $f;
    my $ne;

    if ( $ARGV[ 0 ] ) {
        open( $f, "<$ARGV[ 0 ]" ) or return;
    } else {
        open( $f, "<$ENV{ HOME }/.fsc2/field_stability" ) or return;
    }

    goto done_reading unless defined( $ne = <$f> ) and $ne =~ /^#/;

    goto done_reading unless defined( $ne = <$f> ) and is_numeric( $ne );
    chomp $ne;
    $field = $ne;

    goto done_reading unless defined( $ne = <$f> )
        and $ne =~ /^(Don't set)|(\d\.\d*)$/;
    chomp $ne;
    $sens1 = $ne;

    goto done_reading unless defined( $ne = <$f> ) and $ne =~ /^E\+\d$/;
    chomp $ne;
    $sens2 = $ne;

    goto done_reading unless defined( $ne = <$f> )
        and $ne =~ /^(Don't set)|(\d+(\.\d+)? m?s)$/;
    chomp $ne;
    $tc = $ne;

    goto done_reading unless defined( $ne = <$f> )
        and $ne =~ /^([+-]?\d+)|(unset)$/;
    chomp $ne;
    $phase = $ne if $ne =~ /^[+-]?\d+$/;

    goto done_reading unless defined( $ne = <$f> )
        and $ne =~ /^(Don't set)|(\d\.\d* kHz)$/;
    chomp $ne;
    $mod_freq = $ne;

    goto done_reading unless defined( $ne = <$f> )
        and ( $ne =~ /^unset$/ or is_numeric( $ne ) );
    chomp $ne;
    $mod_amp = $ne unless $ne =~ /^unset$/;

    goto done_reading unless defined( $ne = <$f> ) and
		                     ( $ne =~ /^unset$/ or is_numeric( $ne ) );
    chomp $ne;
    goto done_reading if $ne !~ /^unset$/ and $ne < 0;
    $sec_freq = $ne unless $ne =~ /^unset$/;

    goto done_reading unless defined( $ne = <$f> )
        and $ne =~ /^(Start experiment)|(Test program)|(Load into fsc2)$/;
    chomp $ne;
    $how = $ne;

  done_reading:
    close F;
}


#############################################

sub store_defs {
    my $f;
    my $sens;

    mkdir "$ENV{ HOME }/.fsc2", 0777 unless -e "$ENV{ HOME }/.fsc2";
    open( $f, ">$ENV{ HOME }/.fsc2/field_stability" ) or return;

    $field = 0 if $field eq ".";

    print $f "# Do not edit - created automatically!\n";

    print $f "$field\n$sens1\n$sens2\n$tc\n";

    if ( defined( $phase ) and $phase !~ /^$/ ) {
        print $f "$phase\n";
    } else {
        print $f "unset\n";
    }

    print $f "$mod_freq\n";

    if ( defined( $mod_amp ) and $mod_amp !~ /^$/ ) {
        print $f "$mod_amp\n";
    } else {
        print $f "unset\n";
    }

    if ( defined( $sec_freq ) and $sec_freq !~ /^$/ ) {
        print $f "$sec_freq\n";
    } else {
        print $f "unset\n";
    }

	print $f "$how\n";

    close $f;
}


#############################################

sub sens_check {

    if ( $sens1 =~ /^\d\.\d+/ ) {
        if ( $sens2 eq "E+7" and $sens1 ne "1.0" ) {
            show_message( "Maximum sensitivity is 1.0 E+7." );
            $sens1 = $old_sens1;
            $sens2 = $old_sens2;
            return;
        } elsif ( $sens2 eq "E+1" and $sens1 =~ /^1/) {
            show_message( "Minimum sensitivity is 2.0 E+1." );
            $sens1 = $old_sens1;
            $sens2 = $old_sens2;
            return;
        }
    }

    $old_sens1 = $sens1;
    $old_sens2 = $sens2;
}


#############################################

sub is_numeric {

    my $new_val = shift;
    $new_val =~ /^((\d+\.?(\d+)?)|(\.(\d+)?))?$/;
}


#############################################

sub show_message {
    my $text = shift;

    $mw->messageBox( '-icon' => 'error',
                     '-type' => 'Ok',
                     '-title' => 'Error',
                     '-message' => $text );
}


#############################################


sub do_checks {

    if ( $field =~ /^\.?$/ ) {
        &show_message( "Start field hasn't been set." );
        return -1;
    }

    if ( $field < $ER032M_MIN_FIELD ) {
        &show_message( "Start field is too low." );
        return -1;
    }

    if ( $field > $ER032M_MAX_FIELD ) {
        &show_message( "Start field is too high." );
    }

	if ( $mod_amp !~ /^$/ and $mod_amp > 100 ) {
		&show_message( "Maximum modulation amplitude is 100 G." );
		return -1;
	}

    return 0;
}


#############################################

sub write_out {

    return if &do_checks( ) != 0;

    local *F;
    my $ct;

    open( F, "|fsc2_" . lc $how )
        or die "Can't find utility fsc2_" . lc $how . ".\n";

    print F "DEVICES:

er032m;
er023m;
pci_mio_16e_1;
gg_chopper;


VARIABLES:

field = $field G;
data;
J = 0;
F_data, F_params;
tc, wt;
";
print F "sec_freq = $sec_freq;\n" if $sec_freq !~ /^$/;
print F "

PREPARATIONS:

init_1d( 1, \"Points\", \"Signal / V\" );


EXPERIMENT:

";

print F "chopper_sector_frequency( sec_freq );\n" if $sec_freq !~ /^$/;
print F "

F_data = get_file( \"File for storing data:\" );
F_params = clone_file( F_data, \"dat\", \"par\" );
";

print F "lockin_sensitivity( $sens1$sens2 );\n" if $sens1 !~ /^Don't set$/;
print F "lockin_phase( $phase );\n"
    if defined( $phase ) and $phase =~ /^[+-]?\d+$/;
print F "lockin_ref_freq( $mod_freq );\n" if $mod_freq !~ /^Don't set$/;
print F "lockin_ref_level( $mod_amp G );\n"
	  if defined $mod_amp and $mod_amp !~ /^$/;
    if ( $tc !~ /^Don't set$/ ) {
        print F "tc = $tc;
lockin_time_constant( tc );\n";
        $tc =~ /^(\d+(\.\d+)?) (m?)s$/;
        if ( defined $3 and $3 eq "m" ) {
            $ct = POSIX::floor( $1 / 0.32 + 0.5 );
            $ct = 10 if $ct < 10;
            print F "lockin_conversion_time( " . ( $ct * 3.2e-1 ) . " ms );\n";
        } else {
            $ct = POSIX::floor( $1 / 0.32e-3 + 0.5 );
            $ct = 9999 if $ct > 9999;
            print F "lockin_conversion_time( " . ( $ct * 3.2e-4 ) . " s );\n";
        }
    } else {
        print F "tc = lockin_time_constant( );\n";
    }

print F "
fsave( F_params, \"% Field:                    # G\\n\"
                 \"% Time constant:            # ms\\n\"
                 \"% Sensitivity:              # %\\n\"
                 \"% Phase:                    # Deg\\n\"
                 \"% Mod. Frequency:           # kHz\\n\"
                 \"% Mod. Amplitude:           # %\\n\",
                 field, tc, lockin_sensitivity( ), lockin_phase( ),
				 lockin_ref_freq( ), lockin_ref_level( ) );

save_comment( F_data, \"# \" );

FOREVER {
    J += 1;
    wait( tc );
    data = lockin_get_data( );
    display( J, data );
    fsave( F_data, \"#\\n\", data );
}
";

	close F;

	# Notify the user if sending the program to fsc2 failed for some reasons

	my $text;
	if ( $? != 0 ) {
		 if ( $? >> 8 == 255 ) {
			 $text = "Internal error.";
		 } elsif ( $? >> 8 == 1 ) {
			 $text = "Could not start fsc2.";
		 } else {
			 $text = "Something strange is going on here.";
		 }

		 &show_message( $text ) if $? >> 8 != 0;
	 }
}
