\input texinfo   @c -*-texinfo-*-

@c $Id$
@c
@c Copyright (C) 1999-2002 Jens Thoms Toerring
@c
@c This file is part of fsc2.
@c
@c Fsc2 is free software; you can redistribute it and/or modify
@c it under the terms of the GNU General Public License as published by
@c the Free Software Foundation; either version 2, or (at your option)
@c any later version.
@c
@c Fsc2 is distributed in the hope that it will be useful,
@c but WITHOUT ANY WARRANTY; without even the implied warranty of
@c MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
@c GNU General Public License for more details.
@c
@c You should have received a copy of the GNU General Public License
@c along with fsc2; see the file COPYING.  If not, write to
@c the Free Software Foundation, 59 Temple Place - Suite 330,
@c Boston, MA 02111-1307, USA.

@c %**start of header

@setfilename fsc2.info
@settitle fsc2
@set lastupdate January 4, 2002
@iftex
@afourpaper
@end iftex

@c %**end of header


@syncodeindex fn cp


@titlepage
@sp 4
@center @titlefont{fsc2}
@sp 4
@center A program for the remote control of EPR spectrometers
@sp 2
@center January 2002
@sp 10
@center Jens Thoms T@"orring
@sp 1
@center @email{Jens.Toerring@@physik.fu-berlin.de}
@sp 16
@center Copyright @copyright{} 1999--2002 Jens Thoms T@"orring
@end titlepage


@ifinfo
@direntry
* fsc2: (fsc2). A program for the remote control of EPR spetrometers.
@end direntry
@end ifinfo


@ifinfo
@node Top, , (dir), (dir)
@top Top

This text describes @acronym{fsc2}, a program to control cw- and pulsed
EPR spectrometer. Basically, @acronym{fsc2} is an interpreter to run a
program that describes how the experiment is to be done. After an
overview the syntax to be used is explained. This is followed by a
section about the built-in functions that may be used in the
program. Finally, it is explained who one can write modules for new
devices to be used in the experiment.


@menu
* Overview::                Basic concepts of fsc2.
* GUI::                     The grahical user interface
* EDL::                     Description of EDL the language.
* Built-in Functions::      Built-in functions.
* Device Functions::        Functions for accessing devices.
* Using Pulsers::           How to work with the pulsers
* Command Line Options::    How to invoke @acronym{fsc2}
* Cloning Devices::         Creating modules for identical devices
* Modules::                 How to create new modules.
* Interfacing::             Accessing fsc2 from other programs
* Device Reference::        List of devices and their functions
* Reserved Words::          List of all reserved words.
* Acknowledgments::         The title says it all...
* Copying::                 The GNU General Public License
* Index::                   List of all indexed words.
@end menu

@end ifinfo

@contents

@include overview.texi
@include gui.texi
@include edl.texi
@include builtins.texi
@include devices.texi
@include pulser.texi
@include cmd.texi
@include cloning.texi
@include modules.texi
@include interfacing.texi
@include dev_ref.texi
@include reserved.texi
@include ack.texi
@include gpl.texi

@node Index, , , Top
@unnumbered Index
@printindex cp

@bye
