@c $Id$
@c
@c Copyright (C) 2001 Jens Thoms Toerring
@c
@c This file is part of fsc2.
@c
@c Fsc2 is free software; you can redistribute it and/or modify
@c it under the terms of the GNU General Public License as published by
@c the Free Software Foundation; either version 2, or (at your option)
@c any later version.
@c
@c Fsc2 is distributed in the hope that it will be useful,
@c but WITHOUT ANY WARRANTY; without even the implied warranty of
@c MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
@c GNU General Public License for more details.
@c
@c You should have received a copy of the GNU General Public License
@c along with fsc2; see the file COPYING.  If not, write to
@c the Free Software Foundation, 59 Temple Place - Suite 330,
@c Boston, MA 02111-1307, USA.


@node GUI, EDL, Command Line Options, Top
@chapter GUI

@ifinfo

@menu
* Main Window::        The program's main window
@end menu

@end ifinfo


@node Main Window, , GUI, GUI
@section Main Window

@ifnotinfo

Whenever you start @acronym{fsc2} you will see the following window:

@image{fsc2fig1,11cm}

The large white area in the upper halve is the browser that contains the
text of the current @acronym{EDL} program (after you loaded it). Below
the main browser is another browser which displays error messages as
well as the output from the @acronym{EDL} program. On the right side of
the browsers is a slider that lets you move the border between both
browsers.

On the left side you have a set of buttons:
@itemize @bullet
@item The @code{Load} button opens a file selector that allows you to
select a new @acronym{EDL} program.
@item The @code{Reload} button - when you have edited the currently
loaded @acronym{EDL} program you have to click onto this button to
make @acronym{fsc2} load the changed file.
@item The @code{Edit} button opens an editor with the currently loaded
 @acronym{EDL} program. Which editor will be used depends on the
environment variable @code{EDITOR}, if it isn't set @code{vi} is used as
the default editor.
@item The @code{Test} button lets you check an @acronym{EDL} program 
after it has been loaded. While the test is running the buttons label is
changed to @code{Stop Test} and can be used to abort the test. After the
test finished succesfully the button becomes inactive until a new
program is loaded (or the current program is reloaded).
@item Using the @code{Start} button you start the execution of the
@acronym{EDL} program, i.e.@ you start the experiment.
@item The @code{Quit} button aborts @acronym{fsc2}.
@item Pressing the @code{Help} button will try to start a browser with
the HTML documentation for @acronym{fsc2}. You can select the browser to
use by setting the environment variable @code{BROWSER} to the name of
your favourite browser (at least opera, netscape, konqueror, lynx and
w3m should work without problems). The default browser is Netscape.
@item The @code{Bug report} button will open an editor window
where you can compose a bug report. When you're finished writing the
mail @acronym{fsc2} will let you decide if you want to mail me the bug
report.
@end itemize

@end ifnotinfo

@ifinfo
@ifnothtml

The first window you see when you start @acronym{fsc2} contains the
following elements:
@itemize @bullet
@item At the top the browser for displaying the @acronym{EDL} file to be run
@item Below this another browser where error messages as well as output
from the @acronym{EDL} program will be displayed.
@item On the right side of the browsers is a slider that lets you move
the border between both browsers.
@item The @code{Load} button - when you click onto it a file selector
is shown that allows you to select a new @acronym{EDL} program.
@item The @code{Reload} button - when you have edited the currently
loaded @acronym{EDL} program you have to click onto this button to
make @acronym{fsc2} load the changed file.
@item The @code{Edit} button - when you click onto it an editor will
open up with the curently loaded @acronym{EDL} program. Which
editor will be used depends on the environment variable @code{EDITOR},
if it isn't set @code{vi} is used as the default editor.
@item The @code{Test} button lets you check an @acronym{EDL} program 
after it has been loaded. While the test is running the buttons label is
changed to @code{Stop Test} and can be used to abort the test. After the
test finished succesfully the button becomes inactive until a new
program is loaded (or the current program is reloaded).
@item Using the @code{Start} button you start execution of the
@acronym{EDL} program, i.e.@ you start the measurement.
@item The @code{Quit} button is for leaving @acronym{fsc2}.
@item Pressing the @code{Help} button will start try to start a browser
with the HTML documentation for @acronym{fsc2}. You can select the browser to
use by setting the environment variable @code{BROWSER} to the name of
your favourite browser (at least opera, netscape, konqueror, lynx and
w3m should work without problems). The default browser is Netscape.
@item Finally, the @code{Bug report} button will open an editor window
where you can compose a bug report. When you're finished writing the
mail @acronym{fsc2} will let you decide if you want to mail me the bug
report.
@end itemize

@end ifnothtml
@end ifinfo

In each button one of the characters of the label is underlined. By
pressing the key for this letter each button can be triggered via the
keyboard - but note that, if the underlined letter is an uppercase
character, you have to enter the uppercase character from the keyboard!

While a test of a @acronym{EDL} program is running most of the buttons
can not be used (indicated by their labels becoming grayed out). The
label of the @code{Test} button will become @code{Stop Test} - so if you
want to stop the test press the @code{Test} button again. After a
successful test the @code{Test} button will remain grayed out until a
new program is loaded.

During the test @acronym{fsc2} may detect problems with the
@acronym{EDL} program or even errors. It then will print messages in the
lower browser. There are three categories of messages: Warnings,
messages for severe problems and fatal error messages. Warnings are
printed in green, messages for severe problems in blue and messages for
fatal errors in red (in the latter case the test is also aborted
immediately).

