@c $Id$

@node GUI, EDL, Command Line Options, Top
@chapter GUI

@ifinfo

@menu
* Main Window::        What you see first
@end menu

@end ifinfo


@node Main Window, , GUI, GUI
@section Main Window

@ifnotinfo

Whenever you start @acronym{fsc2} you will see the following window:
@end ifnotinfo

@ifinfo
The first window you see when you start @acronym{fsc2} contains the
following buttons:
@end ifinfo
