#!/usr/bin/perl
# -*- cperl -*-
#
# $Id$
#
# Copyright (C) 1999-2002 Jens Thoms Toerring
#
# This file is part of fsc2.
#
# Fsc2 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# Fsc2 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GNU Emacs; see the file COPYING.  If not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

use strict;
use warnings;

my $fh;
my $missing = 0;

chdir( ".." );

open( $fh, "<MANIFEST" ) or die "Can't open file MANIFEST for reading: $!\n";
while ( <$fh> ) {
	next if /^\s*(#.*)?$/;
	chomp;
	next if -e $_;
	$missing += 1;
	print "$_ is missing\n";
}

if ( $missing ) {
	print "\n $missing files are missing.\n";
} else {
	print "Found all nessecary files.\n";
}
