#!/usr/bin/perl
# -*- cperl -*-
#
#  Copyright (C) 1999-2012 Jens Thoms Toerring
#
#  This file is part of fsc2.
#
#  Fsc2 is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3, or (at your option)
#  any later version.
#
#  Fsc2 is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.


use strict;
use warnings;


my $fh;
my $missing = 0;

chdir( ".." );

open( $fh, "<MANIFEST" ) or die "Can't open file MANIFEST for reading: $!\n";
while ( <$fh> ) {
    next if /^\s*(#.*)?$/;
    chomp;
    next if -e $_;
    $missing += 1;
    print "$_ is missing\n";
}

if ( $missing ) {
    print "\n $missing files are missing.\n";
} else {
    print "Found all nessecary files.\n";
}


# Local variables:
# tab-width: 4
# indent-tabs-mode: nil
# End:
