#!/bin/bash
#
# Copyright (C) 2003-2014  Jens Thoms Toerring
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# To contact the author send email to:  jt@toerring.de


################################################################
# Utility function

function get_reply() {
    test $? -eq 0 || exit 1
    eval $1="`cat /tmp/WITIO_48_reply`"
}


################################################################

function get_module_conf()
{
	if [ -e /etc/modules ]
	then
		echo "/etc/modules";
	elif [ -e /etc/modules.conf ]
	then
		echo "/etc/modules.conf"
	elif [ -e /etc/conf.modules ]
	then
		echo "/etc/conf.modules"
	elif [ -e /etc/modules.conf.local ]
	then
	    echo "/etc/modules.conf.local"
	fi
}


################################################################

function get_major()
{
	echo `grep WITIO_48_MAJOR driver/autoconf.h | awk '{print $3}'`
}


################################################################
# Ask the user for the module paramters

function do_setup() {
	if [ $1 -ne 1 ]
	then
		dialog --yesno \
"   Installation of WITIO-48 driver and library\n\n\
You will now be asked a few questions concerning the\n\
default settings for the driver. If you have problems\n\
understanding what this is all about please read the\n\
README file.\n\n\
             Do you want to continue?" 13 62;

		test $? -eq 0 || exit 0
	fi

	# Ask for the base address of the board, it must be between 0x200 and 0x300
	# in increments of 0x10

	dialog --radiolist \
"  Select base address (press <Space> to select)\n" 17 60 10 \
"0x200" "Port range 0x200-0x20B"           "off" \
"0x210" "Port range 0x210-0x21B"           "off" \
"0x220" "Port range 0x220-0x22B"           "off" \
"0x230" "Port range 0x230-0x23B"           "off" \
"0x240" "Port range 0x240-0x24B"           "off" \
"0x250" "Port range 0x250-0x25B"           "off" \
"0x260" "Port range 0x260-0x26B"           "off" \
"0x270" "Port range 0x270-0x27B"           "off" \
"0x280" "Port range 0x280-0x28B"           "off" \
"0x290" "Port range 0x290-0x29B"           "off" \
"0x2A0" "Port range 0x2A0-0x2AB"           "off" \
"0x2B0" "Port range 0x2B0-0x2BB"           "off" \
"0x2C0" "Port range 0x2C0-0x2CB"           "off" \
"0x2D0" "Port range 0x2D0-0x2DB"           "off" \
"0x2E0" "Port range 0x2E0-0x2EB"           "off" \
"0x2F0" "Port range 0x2F0-0x2FB"           "off" \
"0x300" "Port range 0x300-0x30B	(default)" "on" \
	2> /tmp/WITIO_48_reply

	get_reply BASE

	# Ask for the major device number, it must be between 1 and 254 (or 4094
	# for 2.6 or 3.x kernels) or 0 for a dynamically assigned device number

	if [ ! $IS_NEW_KERNEL ]
	then
		REPEAT=1;
		while [ $REPEAT -ne 0 ]
		do
			MAJOR=0;
			REPEAT=0;
			dialog --inputbox "\
Select the major device number, pick one between 1 and 254\n\
and also compare with/usr/src/linux/Documentation/devices.txt.\n\
Alternatively specify 0 to use a dynamically assigned major\n\
device number." 12 70 "$MAJOR" 2> /tmp/WITIO_48_reply

			get_reply MAJOR
			test -n "$MAJOR" || REPEAT=1
			test -z `echo $MAJOR | tr -d '[:digit:]'` || REPEAT=1
			if [ $REPEAT -eq 0 ]
			then
				test \( $MAJOR -ge 0 -a $MAJOR -le 254 \) || REPEAT=1
			fi
		done
	else
		REPEAT=1;
		while [ $REPEAT -ne 0 ]
		do
			MAJOR=0;
			REPEAT=0;
			dialog --inputbox "\
Select the major device number, pick one between 1 and 4094\n\
and also compare with/usr/src/linux/Documentation/devices.txt.\n\
Alternatively specify 0 to use a dynamically assigned major\n\
device number." 12 70 "$MAJOR" 2> /tmp/WITIO_48_reply

			get_reply MAJOR
			test -n "$MAJOR" || REPEAT=1
			test -z `echo $MAJOR | tr -d '[:digit:]'` || REPEAT=1
			if [ $REPEAT -eq 0 ]
			then
				test \( $MAJOR -ge 0 -a $MAJOR -le 4094 \) || REPEAT=1
			fi
		done
	fi

	# Ask for further compilation options

	dialog --yesno "Build driver with debugging code?" 6 50
	DEBUG=$?

	if [ $DEBUG -eq 0 ]
	then
		dbg="Yes";
	else
		dbg="No"
	fi;

	# Finally get user to set the install directory

	PREFIX="/usr/local"
	dialog --inputbox \
"Finally, please enter the place where to install\n\
    the include files and the library:\n" \
    10 58 "$PREFIX" 2> /tmp/WITIO_48_reply
	get_reply PREFIX
	PREFIX=${PREFIX%%/}    # strip trailing slashes

	# Show user the values he has selected and give him a last chance to back
	# out

	dialog --yesno "\
You selected the following settings for the driver:\n\n\
      Base address:            $BASE\n\
      Major device number:     $MAJOR\n\
      Include debbuging code:  $dbg\n\
      Install directory:       $PREFIX\n\n\
          Create 'driver/autoconf.h'?\n" 12 57

	return $?
}


################################################################
# Create the autoconf.h file

function make_auto() {
	echo "/* Automatically created - change carefully */" > driver/autoconf.h
	echo "" >> driver/autoconf.h
	echo "#define WITIO_48_BASE     $BASE" >> driver/autoconf.h
	echo "#define WITIO_48_MAJOR    $MAJOR" >> driver/autoconf.h
	test $DEBUG -ne 0 || echo "#define WITIO_48_DEBUG" >> driver/autoconf.h
	echo "#define WITIO_48_PREFIX   \"$PREFIX\"" >> driver/autoconf.h
}


################################################################
# Run setup of parameter until the user is satisfied

function do_setup_loop() {
    do_setup $1
    while [ $? -ne  0 ]
	do
        do_setup 0
    done

    make_auto

	# Ask user if she wants the program compiled

    dialog --yesno "\
	Created 'driver/autoconfig.h'\n\
 Continue with compiling everything?\n\n\
(You can return to this point anytime\n\
	  you feel like it.)\n" 10 44

	test $? -eq 0 || exit 0
}


################################################################
# Function that starts the make process after some more checks

function do_compile() {
	# Check that system headers are available

	if [    ! -e $KERNEL_DIR/include/linux/autoconf.h \
		 -a ! -e /usr/include/linux/autoconf.h \
		 -a ! -e $KERNEL_DIR/include/generated/autoconf.h ]
	then
		dialog --msgbox \
"To create the driver for the board the file\n\
$KERNEL_DIR/include/linux/autoconf.h,\n\
$KERNEL_DIR/include/generated/autoconf.h,\n\
or /usr/include/linux/autoconf.h, depending on how old\n\
your kernel is, is required. This file contains vital\n\
information about the kernel the module is intended for.\n\
Please also see additonal information in the README file.\n\n\
Unfortunately, the installation can't proceed.\n" 13 62;
		exit 1;
	fi

	# Compile the driver and the library

	echo "Compiling the driver, please wait..."
	make driver > makelog 2>&1

	if [ $? -ne 0 ]
	then
		dialog --msgbox \
"Sorry, compiling the driver failed.\nSee \"makelog\" for the reasons.\n" 7 40;
    	exit 1;
	fi

	echo "Compiling the library, please wait..."
	make lib >> makelog 2>&1

	if [ $? -ne 0 ]
	then
		dialog --msgbox \
"Sorry, compiling the library failed.\n\
See \"makelog\" for the reasons.\n" 7 45;
    	exit 1;
	fi
}


################################################################

function install_lsb() {
	dialog --yesno "\
Do you want me to copy the init script 'utils/witio_48'\n\
to the init directory '/etc/init.d' and create the\n\
necessary runlevel links so that the WITIO_48 module\n\
gets loaded at boot time and the device files are\n\
             created automatically?" 9 65

	if [ $? -eq 0 ]
	then
		if [ -e /etc/init.d/witio_48 ]
		then
			if [ -e /lib/lsb/remove_initd ]
			then
				/lib/lsb/remove_initd /etc/init.d/witio_48 > /dev/null 2>&1
			else
				/usr/lib/lsb/remove_initd /etc/init.d/witio_48 > /dev/null 2>&1
			fi
			rm -f /etc/init.d/witio_48
		fi
		install -m 744 utils/witio_48 /etc/init.d/witio_48
		if [ -e /lib/lsb/install_initd ]
		then
			/lib/lsb/install_initd /etc/init.d/witio_48
		else
			/usr/lib/lsb/install_initd /etc/init.d/witio_48
		fi
		dialog --msgbox "\
Unless you reboot the system (which is *not* required)\n\
please run the command\n\
\n\
         /etc/init.d/witio_48 start\n\
\n\
    to load the module and create device files.\n\
    If the module is already loaded please use\n\
\n\
         /etc/init.d/witio_48 restart\n\
\n\
      to replace it by the new version." 16 60
	fi
}


################################################################

function install_update_rc() {

	dialog --yesno "\
Do you want me to copy the init script 'utils/witio_48'\n\
to the init directory '/etc/init.d' and create the\n\
necessary runlevel links so that the WITIO_48 module\n\
gets loaded at boot time and the device files are\n\
             created automatically?" 9 65

	if [ $? -eq 0 ]
	then
		install -m 744 utils/witio_48 /etc/init.d/witio_48
		update-rc.d witio_48 defaults

		dialog --msgbox "\
Unless you reboot the system (which is *not* required)\n\
please run the command\n\
\n\
         /etc/init.d/witio_48 start\n\
\n\
    to load the module and create device files.\n\
    If the module is already loaded please use\n\
\n\
         /etc/init.d/witio_48 restart\n\
\n\
      to replace it by the new version." 16 60
	fi
}


################################################################
# Does everything needed for the installation

function do_install()
{
	# Check that user has the necessary permissions for installation

	if [ `id -u` != "0" ]
	then
		dialog --msgbox \
"For installation you need root privileges.\n\
Please become root (or run 'INSTALL' with\n\
'sudo') to continue with the installation.\n" 7 48
		exit 0;
	fi

	MAJOR=$(get_major)
	MODULECONF=$(get_module_conf)

	install_lib
	install_driver
	install_device_files
	install_modules_conf
	install_init_script
	update_dep
	load_module
}


################################################################

function install_lib()
{
	# Ask user if he wants to install the library

	PREFIX=`grep WITIO_48_PREFIX driver/autoconf.h | sed 's/[^\"]*//' | tr -d \"`

	dialog --yesno \
"Do you want to install the library? This involves\n\
copying the following files, if necessary creating\n\
directories that don't exist:\n\n\
 driver/witio_48_drv.h => $PREFIX/include/witio_48_drv.h\n\
 lib/witio_48.h        => $PREFIX/include/witio_48.h\n\
 driver/witio_48_drv.h => $PREFIX/include/witio_48_drv.h\n\
 lib/libwitio_48.a     => $PREFIX/lib/libwitio_48.a\n\
 lib/libwitio_48.so    => $PREFIX/lib/libwitio_48.so" 13 74

	test $? -eq 0 || return

	# Do the basic installation (covered by the makefile)

	make install_lib >> makelog 2>&1
	if [ $? -ne 0 ]
	then
		dialog --msgbox \
"Sorry, installation of libarary failed.\n\
See \"makelog\" for the reasons.\n" 7 45;
    	exit 1
	fi
}


################################################################
# Installs the kernel module

function install_driver()
{
	dkms > /dev/null 2>&1
	if [ $? -eq 0 ]
	then
		dialog --yesno \
"Do you want to install the device driver using dkms?" 5 60
        if [ $? -eq 0 ]
		then
			install_dkms
		else
			install_driver_mech
		fi
	else
		install_driver_mech
	fi
}


################################################################
# Installs the kernel module using dkms

function install_dkms()
{
	if [ -n "`dkms status -m witio_48 -v 1.0`" ]
	then
		dkms uninstall -m witio_48 -v 1.0 -k $KERNEL_VERSION >> makelog 2>&1
		rm -rf /usr/src/witio_48-1.0 >> makelog 2>&1
		cp -r driver /usr/src/witio_48-1.0
	else
		dkms add driver >> makelog 2>&1
	fi

	if [ $? -ne 0 ]
	then
		dialog --msgbox \
"Sorry, Failed to add module to dkms.\n\
See \"makelog\" for the reasons.\n" 7 45;
        exit 1
	fi

	dkms build -m witio_48 -v 1.0 -k $KERNEL_VERSION >> makelog 2>&1
	if [ $? -ne 0 ]
	then
"Sorry, Failed to build module with dkms.\n\
See \"makelog\" for the reasons.\n" 7 45;
        exit 1
	fi

	dkms install -m witio_48 -v 1.0 -k $KERNEL_VERSION >> makelog 2>&1
	if [ $? -ne 0 ]
	then
"Sorry, Failed to unstall module with dkms.\n\
See \"makelog\" for the reasons.\n" 7 45;
        exit 1
	fi

	DKMS_INSTALL=1
}


################################################################
# Installs the kernel module "manually"

function install_driver_mech()
{
	if [ $IS_NEW_KERNEL ]
	then
		MOD_INST_AS="/lib/modules/$KERNEL_VERSION/kernel/extra/witio_48.ko";
		LOCAL_NAME="driver/witio_48.ko";
	else
		MOD_INST_AS="/lib/modules/$KERNEL_VERSION/misc/witio_48.o";
		LOCAL_NAME="driver/witio_48.o ";
	fi

	dialog --yesno \
"Do you want to install the device driver manually?\n\
We'll copy the following file, if necessary creating\n\
directories that don't exist:\n\n\
$LOCAL_NAME => $MOD_INST_AS" 12 75

    if [ $? -ne 0 ]
	then
		NO_DRIVER_INSTALL=1
		return
	fi

	make install_driver >> makelog 2>&1

	if [ $? -ne 0 ]
	then
		dialog --msgbox \
"Sorry, installation of the driver failed.\n\
See \"makelog\" for the reasons.\n" 7 50;
    	exit 1
	fi
}


################################################################

function install_device_files()
{
	# Find out if user wants to create the device file for the board, but only
	# if the major device number isn't assigned dynamically (isn't set to 0).

	test $MAJOR -ne 0 || return

	dialog --yesno \
"Do you want to create the device file\n\n\
        /dev/witio_48\n\n\
   for the RULBUS interface?"  9 46

    test $? -eq 0 || return

    if [ -e /dev/witio_48 ]
	then 
		dialog --yesno \
"A device file /dev/witio_48 already exists.\n\
Delete existing file and replace with a new one?" 7 54;

        if [ $? -eq 0 ]
		then
			rm -f /dev/witio_48
			mknod /dev/witio_48 c $MAJOR 0
			chmod 666 /dev/witio_48
		fi
	else
		mknod /dev/witio_48 c $MAJOR 0
		chmod 666 /dev/witio_48
	fi
}


################################################################
# In the olden times we needed to set up /etc/modules.conf or
# /etc/modules/conf.modules or /etc/modules.conf.local if the
# device major number was set staticatlly (i.e. set to non-zero)
# to get the module loaded at boot time.  And in modern times
# (with /etc/modules) we can request the same (independent of
# the major device number) by simply putting the driver's name
# into /etc/modules.

function install_modules_conf()
{
	if [    -z $MODULECONF \
		 -o \( $MAJOR -eq 0 -a $MODULECONF != "/etc/modules" \) ]
	then
		return
	fi

	if [ $MODULECONF = "/etc/modules" ]
	then
		dialog --yesno \
"Add witio_48 to /etc/modules to have\n\
the driver loaded on reboots?" 7 50
        test $? -eq 0 || return

		grep '^[ \t]*witio_48[ \t]*\(#.*\)*$' $MODULECONF 2<&1 > /dev/null;
		if [ $? -ne 0 ]
		then
			cp $MODULECONF $MODULECONF.bak
			echo "witio_48" >> $MODULECONF
		fi
		return
	fi

	dialog --yesno \
"Update $MODULECONF to include the driver? (Old\n\
version will be saved as $MODULECONF.bak.)" 7 62
    test $? -eq 0 || return

	cp $MODULECONF $MODULECONF.bak

	PATTERN="^[[:space:]]*alias[[:space:]+]char-major-$MAJOR[[:space:]+]"
	PATTERN2="^[[:space:]]*pre-install[[:space:]+]witio_48[[:space:]+]"

	LINE=`grep $PATTERN $MODULECONF`
	if [ $? -eq 0 ]
	then
		LINE2=`grep $PATTERN2 $MODULECONF`
		if [ $? -eq 0 ]
		then
			grep -v $PATTERN $MODULECONF | grep -v $PATTERN2 > /tmp/`basename $MODULECONF`
			echo "#$LINE2" >> /tmp/`basename $MODULECONF`
			echo "#$LINE" >> /tmp/`basename $MODULECONF`
		else
			grep -v $PATTERN $MODULECONF > /tmp/`basename $MODULECONF`
			echo "#$LINE" >> /tmp/`basename $MODULECONF`
		fi

		LINE=`grep "^[[:space:]]*options[[:space:]+]witio_48" /tmp/\`basename $MODULECONF\``;
		if [ $? -eq 0 ]
		then
			mv /tmp/`basename $MODULECONF` /tmp/`basename $MODULECONF`2
			grep -v "$LINE" /tmp/`basename $MODULECONF`2 > /tmp/`basename $MODULECONF`
			rm -f /tmp/`basename $MODULECONF`2
			echo "#$LINE" >> /tmp/`basename $MODULECONF`
		fi

		mv /tmp/`basename $MODULECONF` $MODULECONF
	fi

	echo "pre-install witio_48 modprobe \"-k\" \"parport\"" >> $MODULECONF
	echo "alias char-major-$MAJOR witio_48" >> $MODULECONF
}


################################################################
# In case the major device number is selected dynamically and
# we're not on a newer system with an /etc/modules file a script
# can be installed for loading the device driver and creating the
# devide file at boot time. Ask the user if this should be done
# and then try to install the script.

function install_init_script()
{
	if [ $MAJOR -ne 0 -o $MODULECONF = "/etc/modules" ]
	then
		return
	fi

	dialog --yesno \
"Should a script be installed to load the driver\n\
and recreate the device file on reboot?" 7 65

	test $? -eq 0 || return

	# Try to install the init.d script

	if [    -d /etc/init.d \
		-a -e /lib/lsb/init-functions ]
	then
		if [    \(    -e /lib/lsb/install_initd \
			 -o -e /usr/lib/lsb/install_initd \) \
			 -a \(    -e /lib/lsb/remove_initd \
			       -o -e /usr/lib/lsb/remove_initd \) ]
		then
			install_lsb
		elif [ -e /usr/sbin/update-rc.d ]
		then
			install_update_rc
		else
			dialog --msgbox "\
Sorry, don't know how to install a script that automatically\n\
loads the RULBUS module loaded at boot time and creates the\n\
device file. Please change the script 'witio_48' in the\n\
'util' subdirectory to fit your needs and install it\n\
in the directory for init scripts yourself." 12 70
		fi
	fi
}


################################################################
# Updates the modules.dep file for the currently run kernel

function update_dep()
{
	if [ -n "$NO_DRIVER_INSTALL" -o -n "$DKMS_INSTALL" ]
	then
		return
	fi

	dialog --yesno \
"Do you want to update the modules dependency\n\
file /lib/modules/$KERNEL_VERSION/modules.dep\n\
using the command 'depmod'?" 8 55
   test $? -ne 0 || depmod $KERNEL_VERSION -a >/dev/null
}


################################################################
# Tries to load the module

function load_module()
{
	if [ -n "$NO_DRIVER_INSTALL" ]
	then
		return
	fi

	dialog --yesno \
"Do you want to load the modules into the\n\
kernel? Make sure no program is using it!" 6 50
	test $? -eq 0 || return

	# Check if the module is already loaded and try to unload it

	lsmod | grep '^witio_48[ \t]' > /dev/null 2>&1
	if [ $? -eq 0 ]
	then
		rmmod witio_48 >> makelog 2>&1
		if [ $? -ne 0 ]
		then
			dialog --msgbox \
"Failed to unload running module, so the\n\
new module could not be loaded. See\n\
\"makelog\" for the reasons." 8 45
			return
		fi
    fi

	# Now try to load it

	echo "modprobe witio_48" >> makelog
	modprobe witio_48 >> makelog 2>&1
	if [ $? -ne 0 ]
	then
		dialog --msgbox \
"Failed to load module into the kernel.\n\
See \"makelog\" for the reasons." 7 42
   fi
}


################################################################
# Chooses either compiling or installing (called at the start
# when the include/autoconf.h and driver/board exist)

function pref_comp() {
	dialog --radiolist "\
  What do you want to do next?\n\
   (press <Space> to select)"  \
   10 53 2 \
   "Setup  "  "Set the board driver parameters" "off" \
   "Compile"  "Compile the driver and library"  "on"  \
    2> /tmp/WITIO_48_reply

	get_reply MTYPE

	test $MTYPE != "Setup" || do_setup_loop 1
}


################################################################
# Chooses between setup, compilation or installation (called at
# the start when include/autoconf.h and driver/board as well as
# the compiled library and driver exist)

function pref_inst() {
	dialog --radiolist "\
  What do you want to do next?\n\
   (press <Space> to select)"  \
   11 53 3 \
   "Setup  "  "Set the board driver parameters" "off" \
   "Compile"  "Compile driver and library"      "off" \
   "Install"  "Install driver and library"      "on"  \
    2> /tmp/WITIO_48_reply

	get_reply MTYPE

	case $MTYPE in
		Setup  )
			do_setup_loop 1
			do_compile 0
			do_install
			;;

		Compile)
			make clean
			do_compile 1
			do_install
			;;

		Install)
			do_install
			;;
	esac
}


################################################################
# Function sets the variable KENREL_VERSION to a string with 
# the name of the kernel we're supposed to compile for.

function get_kernel_version() {

	if [ -n "$WITIO_48_KERNEL_SOURCE" ]
	then
		KERNEL_DIR=$WITIO_48_KERNEL_SOURCE;
	else
		KERNEL_DIR="/lib/modules/`uname -r`/build";
		if [ -z "$KERNEL_DIR" ]
		then
			KERNEL_DIR="/usr/src/linux";
		fi
	fi

	if [ -z "$KERNEL_DIR" ]
	then
		dialog --msgbox "\n\
Failed to find the kernel headers which are needed to\n\
compile the module. Either install the appropriate\n\
package or set the variable 'WITIO_48_KERNEL_SOURCE'\n\
to the location of the kernel headers." 9 60;
		exit 1;
	fi

	KERNEL_VERSION=`grep UTS_RELEASE                                 \
		            $KERNEL_DIR/include/generated/utsrelease.h       \
                    2>/dev/null |                                    \
				    sed 's/^[^"]\+"\([^"]\+\)".*$/\1/' 2>/dev/null`;
	if [ -z "$KERNEL_VERSION" ]
	then
		KERNEL_VERSION=`grep UTS_RELEASE                                \
			            $KERNEL_DIR/include/linux/utsrelease.h          \
                        2>/dev/null |                                   \
				   s    ed 's/^[^"]\+"\([^"]\+\)".*$/\1/' 2>/dev/null`;
	fi
	if [ -z "$KERNEL_VERSION" ]
	then
		KERNEL_VERSION=`grep UTS_RELEASE
		                     $KERNELDIR/include/linux/version.h \
                       2>/dev/null |
				       sed 's/^[^"]\+"\([^"]\+\)".*$/\1/' 2>/dev/null`;
    fi
    if [ -z "$KERNEL_VERSION" ]
	then
        KERNEL_VERSION=`make --quiet -C $KERNEL_DIR kernelrelease 2>/dev/null`;
	fi

	if [ -z "$KERNEL_VERSION" ]
	then
		dialog --msgbox "\
Sorry, can't determine kernel version under the assumption\n\
that kernel sources are at '$KERNEL_DIR'" 6 64;
		exit 1
	fi

	KV_MAJOR=`echo $KERNEL_VERSION | sed 's/^\([0-9]\+\)\..*$/\1/' 2>/dev/null`
	KV_MINOR=`echo $KERNEL_VERSION | \
              sed 's/^[0-9]\+\.\([0-9]\+\)\..*$/\1/' 2>/dev/null`
	if [ $KV_MAJOR -lt 2 -o $KV_MINOR -le 4 ]
	then
		IS_NEW_KERNEL=0;
	else
		IS_NEW_KERNEL=1;
	fi
}


################################################################
# Main part of the installation script

trap "rm -f /tmp/WITIO_48_reply" 0 1 2 15

export DIALOGRC=./.INSTALLrc

# We need dialog so check if it's available

DIALOG=`which dialog`
if [ $? -eq 1 ]
then
    echo "Sorry, you need the 'dialog' utility to run this script!";
    exit 1;
fi


# Get the kernel version

get_kernel_version;
if [    $KV_MAJOR -ne 3 \
	 -a $KV_MAJOR -ne 4 \
	 -a \(    $KV_MAJOR -ne 2 \
           -o \( $KV_MINOR -ne 4 -a $KV_MINOR -ne 6 \) \) ]
then
    dialog --yesno \
"This package is only tested with 2.4, 2.6 and 3.x\n\
kernels. There could be problems with other kernels.\n\n\
           Do you want to continue?" 8 60
    test $? -eq 0 || exit 0
fi

rm -f makelog > /dev/null 2>&1

if [ ! -e driver/autoconf.h ]
then
   do_setup_loop 0
   do_compile 0
   do_install
else
    if [    \( ! $IS_NEW_KERNEL -a ! -e driver/witio_48.o  \)  \
         -o \(   $IS_NEW_KERNEL -a ! -e driver/witio_48.ko \)  \
		 -o ! -e lib/libwitio_48.a                               \
		 -o ! -e lib/libwitio_48.so ]
	then
        pref_comp
        do_compile 0
        do_install
    else
        pref_inst
    fi
fi

dialog --msgbox "\
Ok, you're hopefully done with creating and\n\
installing the driver and the library." 7 50;

exit 0
